name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Install x11
      run: sudo apt-get install pkg-config xorg libxi-dev
    - name: Build
      run: cargo build
